// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A product recommendation AI agent.
 *
 * - recommendProducts - A function that handles the product recommendation process.
 * - RecommendProductsInput - The input type for the recommendProducts function.
 * - RecommendProductsOutput - The return type for the recommendProducts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendProductsInputSchema = z.object({
  viewingHistory: z
    .array(z.string())
    .describe('The list of product IDs that the user has viewed.'),
  currentProductId: z.string().optional().describe('The ID of the product currently being viewed, if any.'),
  numberOfRecommendations: z.number().default(3).describe('The number of product recommendations to return.'),
});
export type RecommendProductsInput = z.infer<typeof RecommendProductsInputSchema>;

const RecommendProductsOutputSchema = z.object({
  productIds: z
    .array(z.string())
    .describe('The list of recommended product IDs based on the viewing history.'),
});
export type RecommendProductsOutput = z.infer<typeof RecommendProductsOutputSchema>;

export async function recommendProducts(input: RecommendProductsInput): Promise<RecommendProductsOutput> {
  return recommendProductsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendProductsPrompt',
  input: {schema: RecommendProductsInputSchema},
  output: {schema: RecommendProductsOutputSchema},
  prompt: `You are a product recommendation expert for an online store selling handcrafted wooden goods. Given a user's viewing history, you will recommend other products that the user may be interested in.

  Return {{numberOfRecommendations}} product IDs.

  Here is the user's viewing history:
  {{#if viewingHistory}}
  {{#each viewingHistory}}- {{{this}}}
  {{/each}}
  {{else}}
  The user has no viewing history.
  {{/if}}

  {{#if currentProductId}}
  The user is currently viewing product ID: {{{currentProductId}}}
  Take that into account when generating recommendations.
  {{/if}}`,
});

const recommendProductsFlow = ai.defineFlow(
  {
    name: 'recommendProductsFlow',
    inputSchema: RecommendProductsInputSchema,
    outputSchema: RecommendProductsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
